import type { Metadata } from "next";
import 'modern-normalize';
import "./globals.css";
import Header from "@/components/Header/Header";
import { comfortaa, lato } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${lato.className} ${comfortaa.className}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
